#!/bin/bash

# =============================================
#  Constants
# =============================================
assets_dir="img"

tmp_dir=".tmp"

css_file="gnome-shell.css"

gresource_dest="../../gnome-shell-theme.gresource"


# =============================================
#  Copy all assets into $tmp_dir
#
#  Some asset url's are hardcoded into the
#  gnome-shell .js files and point to the
#  theme's root dir.
#
#  To prevent any crashes, copy all assets
#  into one dir before generating the
#  gresource file.
# =============================================
echo -e "\e[34mGenerating gresource file...\e[0m"

trap 'rm -rf $tmp_dir; exit' INT TERM EXIT

mkdir -p "$tmp_dir"

find "$assets_dir" -type f -execdir cp -f {} "$PWD/$tmp_dir/" \;


# =============================================
#  Modify url's in css file
# =============================================
regex="(url\([\"\']*).*/(.*\))"

sed -r "s:$regex:\1\2:" "$css_file" > "$tmp_dir/gnome-shell.css"


# =============================================
#  Create gresource.xml file
# =============================================
echo "<?xml version='1.0' encoding='UTF-8'?><gresources><gresource prefix='/org/gnome/shell/theme'>" \
     > "$tmp_dir/gnome-shell-theme.gresource.xml"


for i in "$tmp_dir"/*; do
    [[ ${i##*.} =~ svg|png ]] || continue

    echo "<file>${i##*/}</file>" \
         >> "$tmp_dir/gnome-shell-theme.gresource.xml"
done


echo "<file>gnome-shell.css</file></gresource></gresources>" \
     >> "$tmp_dir/gnome-shell-theme.gresource.xml"


# =============================================
#  Create gresource file
# =============================================
glib-compile-resources --sourcedir="$tmp_dir" \
                       --target="$gresource_dest" \
                       "$tmp_dir/gnome-shell-theme.gresource.xml"


echo -e "\e[32mGresource file generated!\e[0m"
